AWSTemplateFormatVersion: '2010-09-09'
Description: 'NAT Gateway Cloudformation tamplate.'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentVPCStack
      - ParentAlertStack
      - Environment
    - Label:
        default: 'NatGateway Parameters'
      Parameters:
      - SubnetZone
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC'
    Type: String
  SubnetZone:
    Description: 'Subnet zone.'
    Type: String
    Default: A
    AllowedValues:
    - A
    - B
    - C
  Environment:
    Description: 'Environment Name For Tagging'
    Type: String
    Default: "undefined"
Resources:
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
      Tags: 
      - Key: Environment
        Value: !Sub ${Environment}
  NatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      Tags: 
      - Key: Environment
        Value: !Sub ${Environment}
      AllocationId: !GetAtt 'EIP.AllocationId'
      SubnetId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-Subnet${SubnetZone}Public'}
  Route:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-RouteTable${SubnetZone}Private'}
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: !Ref NatGateway
Outputs:
  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
  IPAddress:
    Description: 'The public IP address of the NAT gateway.'
    Value: !Ref EIP
    Export:
      Name: !Sub '${AWS::StackName}-IPAddress'
